name: Docker Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPOSITORY }}:frontend-${{ github.ref_name }}
            ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPOSITORY }}:frontend-latest

      - name: Trigger Deploy repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          repository: constitution-recipes/Deploy
          event-type: frontend-updated
